server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main

          uri: https://github.com/diegovaldes23/TingesoLab2
          search-paths: config-data
  application:
    name: config-service
