apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-estudiantes-deployment
  labels:
    app: backend-estudiantes-deployment
spec:
  selector:
    matchLabels:
      app: backend-estudiantes-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-estudiantes-deployment
    spec:
      containers:
        - name: topeducation-estudiantes-mysql
          image: diez2332/topeducation-estudiante-mysql:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_ESTUDIANTES
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: MYSQL_DB_ESTUDIANTES
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: estudiante-service
  labels:
    app: estudiante-service
spec:
  selector:
    app: backend-estudiantes-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer