apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  MYSQL_USER: ZGllZ28=
  MYSQL_PASSWORD: cm9vdA==

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-credentials
type: Opaque
data:
  MYSQL_ROOT_USER: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
