apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres
  #base de dato Cuotas
  POSTGRES_DB_CUOTAS: cuota
  #base de dato Estudiantes
  POSTGRES_DB_ESTUDIANTES: estudiante
  #base de dato Resumen
  POSTGRES_DB_RESUMEN: resumen
